CREATE SEQUENCE SEQ_CARROS
START WITH 1
INCREMENT BY 1;

CREATE TABLE CARROS (
  id NUMBER(4) PRIMARY KEY,
  placa VARCHAR2(7) NOT NULL,
  modelo VARCHAR2(50),
  fabricante VARCHAR2(30),
  cor VARCHAR2(30)
);