INSERT INTO MULTAS (id, id_carro, data, valor, descricao, paga)
VALUES (SEQ_MULTAS.NEXTVAL, 24, TO_DATE('2024-08-15', 'YYYY-MM-DD'), 150.00, 'ULTRAPASSAR PELO ACOSTAMENTO', 'N');

INSERT INTO MULTAS (id, id_carro, data, valor, descricao, paga)
VALUES (SEQ_MULTAS.NEXTVAL, 24, TO_DATE('2024-07-22', 'YYYY-MM-DD'), 200.00, 'ESTACIONAR SOBRE FAIXA DESTINADA A PEDESTRE', 'S');

INSERT INTO MULTAS (id, id_carro, data, valor, descricao, paga)
VALUES (SEQ_MULTAS.NEXTVAL, 24, TO_DATE('2024-09-01', 'YYYY-MM-DD'), 300.00, 'AVANCAR O SINAL VERMELHO DO SEMAFORO', 'N');

INSERT INTO MULTAS (id, id_carro, data, valor, descricao, paga)
VALUES (SEQ_MULTAS.NEXTVAL, 24, TO_DATE('2024-06-30', 'YYYY-MM-DD'), 100.00, 'CONDUZIR O VEICULO REGISTRADO QUE NAO ESTEJA DEVIDAMENTE LICENCIADO', 'S');

INSERT INTO MULTAS (id, id_carro, data, valor, descricao, paga)
VALUES (SEQ_MULTAS.NEXTVAL, 24, TO_DATE('2024-08-20', 'YYYY-MM-DD'), 75.00, 'DEIXAR O CONDUTOR DE USAR O CINTO SEGURANCA', 'N');
