SELECT
    CARROS.ID,
    CARROS.PLACA,
    CARROS.MODELO,
    CARROS.FABRICANTE,
    CARROS.COR,
    COUNT(MULTAS.ID) AS total_multas
FROM
    CARROS
left JOIN
    MULTAS
    ON MULTAS.ID_CARRO = CARROS.ID
GROUP BY
    CARROS.ID,
    CARROS.PLACA,
    CARROS.MODELO,
    CARROS.FABRICANTE,
    CARROS.COR
ORDER BY
	COUNT(MULTAS.ID) DESC;